POST http://localhost:3000/user/signup 
Content-Type: application/json

{
   "name": "admin", 
   "email": "admin@gmail.com", 
   "password": "adm123", 
   "role": "ADMIN"
}

### 
POST http://localhost:3000/user/login 
Content-Type: application/json

{
   "email": "admin@gmail.com", 
   "password": "adm123"
}

### 
POST http://localhost:3000/product/insert 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNkOTM4MWVkLTVhNTMtNDg2Yy05ZGY3LTY3NDdjOGYwYzg0NiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDYwOTM0NSwiZXhwIjoxNjYwNjA5OTQ1fQ.YIIJrOJBwyFy-p_A_AIeYjp08oDhha2pCS-3ceb-NIg Content-Type: application/json

{
   "name": "produto1", 
   "tag": ["tag1", "tag3"]
}

### 
GET http://localhost:3000/product/

### 
GET http://localhost:3000/product/{:id}