###
POST http://localhost:3003/users
Content-Type: application/json

{
   "name": "Elisa",
   "email": "lizzbeth.lizz.diaz@gmail.com",
   "password": "568932l"
}

###
GET http://localhost:3003/users

###
POST http://localhost:3003/products
Content-Type: application/json

{
   "name": "Notebook",
   "price": 2934.99,
   "image_url": "https://i.picsum.photos/id/0/5616/3744.jpg?hmac=3GAAioiQziMGEtLbfrdbcoenXoWAW-zlyEAMkfEdBzQ"
}

###
GET http://localhost:3003/products

